package ar.edu.uade.ia.integrations.backOffice.authorization;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-11-06T12:31:50.919-03:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "PrestadorAutorizadoService", 
                  wsdlLocation = "file:/home/ebarbin/wildfly-11.0.0.Beta1/bin/bo.wsdl",
                  targetNamespace = "http://soap.servicios/") 
public class PrestadorAutorizadoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.servicios/", "PrestadorAutorizadoService");
    public final static QName ServiciosBO_002fPrestadorAutorizadoPort = new QName("http://soap.servicios/", "ServiciosBO/PrestadorAutorizadoPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/ebarbin/wildfly-11.0.0.Beta1/bin/bo.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PrestadorAutorizadoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/ebarbin/wildfly-11.0.0.Beta1/bin/bo.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PrestadorAutorizadoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PrestadorAutorizadoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrestadorAutorizadoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PrestadorAutorizadoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PrestadorAutorizadoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PrestadorAutorizadoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ServiciosBO_002fPrestadorAutorizado
     */
    @WebEndpoint(name = "ServiciosBO/PrestadorAutorizadoPort")
    public ServiciosBO_002fPrestadorAutorizado getServiciosBO_002fPrestadorAutorizadoPort() {
        return super.getPort(ServiciosBO_002fPrestadorAutorizadoPort, ServiciosBO_002fPrestadorAutorizado.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiciosBO_002fPrestadorAutorizado
     */
    @WebEndpoint(name = "ServiciosBO/PrestadorAutorizadoPort")
    public ServiciosBO_002fPrestadorAutorizado getServiciosBO_002fPrestadorAutorizadoPort(WebServiceFeature... features) {
        return super.getPort(ServiciosBO_002fPrestadorAutorizadoPort, ServiciosBO_002fPrestadorAutorizado.class, features);
    }

}
