package ar.edu.uade.ia.integrations;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-10-08T11:59:23.914-03:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "ManageBackOfficeService", 
                  wsdlLocation = "file:/home/ebarbin/proy/uade-ia-grupo7/back/workspace/portal-seven-standalone/src/ManageBackOffice.wsdl",
                  targetNamespace = "http://integrations.ia.uade.edu.ar/") 
public class ManageBackOfficeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://integrations.ia.uade.edu.ar/", "ManageBackOfficeService");
    public final static QName ManageBackOfficePort = new QName("http://integrations.ia.uade.edu.ar/", "ManageBackOfficePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/ebarbin/proy/uade-ia-grupo7/back/workspace/portal-seven-standalone/src/ManageBackOffice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ManageBackOfficeService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/ebarbin/proy/uade-ia-grupo7/back/workspace/portal-seven-standalone/src/ManageBackOffice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ManageBackOfficeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ManageBackOfficeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManageBackOfficeService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ManageBackOfficeService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ManageBackOfficeService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ManageBackOfficeService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ManageBackOffice
     */
    @WebEndpoint(name = "ManageBackOfficePort")
    public ManageBackOffice getManageBackOfficePort() {
        return super.getPort(ManageBackOfficePort, ManageBackOffice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManageBackOffice
     */
    @WebEndpoint(name = "ManageBackOfficePort")
    public ManageBackOffice getManageBackOfficePort(WebServiceFeature... features) {
        return super.getPort(ManageBackOfficePort, ManageBackOffice.class, features);
    }

}
