package ar.edu.uade.ia.integrations;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-10-08T11:59:23.834-03:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://integrations.ia.uade.edu.ar/", name = "ManageBackOffice")
@XmlSeeAlso({ObjectFactory.class})
public interface ManageBackOffice {

    @WebMethod
    @RequestWrapper(localName = "autorizeHotelOffer", targetNamespace = "http://integrations.ia.uade.edu.ar/", className = "ar.edu.uade.ia.integrations.AutorizeHotelOffer")
    @ResponseWrapper(localName = "autorizeHotelOfferResponse", targetNamespace = "http://integrations.ia.uade.edu.ar/", className = "ar.edu.uade.ia.integrations.AutorizeHotelOfferResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ar.edu.uade.ia.integrations.BackOfficeResponse autorizeHotelOffer(
        @WebParam(name = "arg0", targetNamespace = "")
        ar.edu.uade.ia.integrations.BackOfficeRequest arg0
    );
}
